[package]
name = "bhi"
version = "0.0.1"
authors = ["sovietbehemoth"]
edition = "2018"

[dependencies]
image = "0.23.14"
druid = "0.7.0"
snap = "1"
[dependencies.sdl2]
version = "0.32.2"
features = ["gfx"]